AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - Gemfile
    - Gemfile.lock
    - 'config/**/*'
    - bin/**/*

Layout/LineLength:
  Enabled: true
  Max: 100

Metrics/MethodLength:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/api/v1/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantFreeze:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false
  Exclude:
    - 'config/**/*'
    - test/

Style/ClassAndModuleChildren:
  Exclude:
    - 'config/**/*'
    - test/**/*

Lint/EmptyBlock:
  Exclude:
    - test/**/*

Layout/TrailingWhitespace:
  Exclude:
    - test/**/*

Style/FormatStringToken:
  EnforcedStyle: template
